# Generated by Django 4.2.11 on 2024-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('color', models.TextField()),
                ('font', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('no_of_ratings', models.IntegerField(default=0)),
                ('images', models.ManyToManyField(blank=True, to='story.image')),
                ('text', models.ManyToManyField(blank=True, to='story.textentry')),
            ],
        ),
    ]
