# Generated by Django 4.2.11 on 2024-05-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='color',
            field=models.TextField(default='#ffffff'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='font',
            field=models.TextField(default='Chalkduster'),
        ),
    ]
